### ISSUE TITLE
Provide a Docker + docker-compose + Makefile environment for developers

### ISSUE THREAD

**Issue by marien-probesys** [fusionSuite/FusionSuite#7]
We could provide an environment for developers based on Docker and docker-compose. Added to a Makefile, this would allow to start the environment with a simple:

```console
$ make start
```

or run the tests/linters with:

```console
$ make tests
$ make lint
```

**Comment by ddurieux** [comment]
@LaurentLienhard has created docker images here: https://github.com/LaurentLienhard/FusionSuite-Docker

**Comment by marien-probesys** [comment]
Indeed, but I can see few problems:

- Dockerfiles are not provided :p
- local source code is not mounted in the Docker containers, so it's not usable in a development environment
- the Docker config should be provided directly in the repositories (less Git repositories, facilitate the config, always in sync with the code requirements)

**Comment by LaurentLienhard** [comment]
Yes sorry this does not necessarily respect good practices but I am a beginner on docker ;-)

**Comment by marien-probesys** [comment]
(my checklist of the things to do)

Backend (https://github.com/fusionSuite/backend/pull/19):

- [x] Create a PHP Dockerfile (with `composer php7.4-fpm php7.4-mysql php7.4-xml`)
- [x] Create a docker-compose file with Nginx, PHP and MariaDB
- [x] Create commands wrappers for `php` and `mariadb` (under `docker/bin`)
- [x] Create a Makefile (targets: `docker-start docker-clean install setup test lint lint-fix help`)

Frontend (https://github.com/fusionSuite/frontend/pull/23):

- [x] Create a NodeJs Dockerfile (with `yarn`)
- [x] Create a docker-compose file with NodeJs
- [x] Create commands wrappers for `npm`, `ng` and `yarn`
- [x] Adapt the Makefile so the commands can be also executed in the Docker container

Documentation (https://github.com/fusionSuite/documentation/pull/27):

- [x] Create a Makefile (targets: `start install help`)
- [x] Adapt the documentation to use the `make` commands
